apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: n9z7b3bmj-nodejs 
  janus-idp.io/tekton: n9z7b3bmj-nodejs
  backstage.io/kubernetes-id: n9z7b3bmj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n9z7b3bmj-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  