apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: n9z7b3bmj-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:6dbb508fb3d99547a5787b32fa56decf6ac6bf53@sha256:54efd5d86feef55e139ee2fc4b3d3024b624715c5b77a1f19fda8da6a6dde395
          name: container-image
