apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: n9z7b3bmj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n9z7b3bmj-nodejs 
  name: n9z7b3bmj-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: n9z7b3bmj-nodejs
    weight: 100 
